name: news-classification
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9
  
  # Core scientific computing
  - numpy>=1.24.3
  - pandas>=2.0.3
  - scipy>=1.11.1
  - scikit-learn>=1.3.0
  
  # PyTorch ecosystem
  - pytorch>=2.0.1
  - torchvision>=0.15.2
  - pytorch-cuda=11.8  # Adjust based on your CUDA version
  
  # Visualization
  - matplotlib>=3.7.1
  - seaborn>=0.12.2
  - plotly>=5.15.0
  
  # Development tools
  - jupyter
  - ipykernel
  - nb_conda_kernels
  
  # System tools
  - git
  - curl
  - wget
  
  # R dependencies (for data collection)
  - r-base>=4.3.0
  - r-essentials
  - r-rvest
  - r-httr
  - r-jsonlite
  - r-dplyr
  - r-stringr
  - r-lubridate
  
  # Pip dependencies
  - pip
  - pip:
    # NLP libraries
    - transformers>=4.30.2
    - tokenizers>=0.13.3
    - nltk>=3.8.1
    - jieba>=0.42.1
    
    # Machine learning
    - optuna>=3.2.0
    
    # API and web
    - openai>=0.27.8
    - requests>=2.31.0
    - aiohttp>=3.8.4
    - asyncio-throttle>=1.0.2
    
    # Data handling
    - pyyaml>=6.0
    - jsonlines>=3.1.0
    - tqdm>=4.65.0
    - datasets>=2.13.1
    
    # Monitoring
    - tensorboard>=2.13.0
    - wandb>=0.15.4
    
    # Utilities
    - python-dotenv>=1.0.0
    - click>=8.1.5
    - colorlog>=6.7.0
    - rich>=13.4.2
    
    # Statistical analysis
    - statsmodels>=0.14.0
    - pingouin>=0.5.3
    
    # Development tools
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - black>=23.7.0
    - flake8>=6.0.0
    - mypy>=1.4.1
    
    # Additional R packages (install via pip for better integration)
    - rpy2>=3.5.12
